services:
  serving:
    build:
      context: ..
      dockerfile: serving/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../data:/data
      - ../artifacts:/artifacts
    networks:
      - prod_net
    restart: unless-stopped

networks:
  prod_net:
    name: prod_net
    driver: bridge
